# -*- coding: utf-8 -*-
"""count_verbs_eng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlHVgHF4n3MlvkyUNJaLm4emobazuOFx
"""

pip install conllu

from conllu import parse_incr

from google.colab import files
import io

uploaded = files.upload()

def count_verbs_in_sentence(file_data):
    verb_count = []
    file_content = io.StringIO(file_data.decode("utf-8"))

    for tokenlist in parse_incr(file_content):
        count = 0
        for token in tokenlist:
            if isinstance(token, dict) and token.get('upos') == "VERB":
                count += 1
        verb_count.append(count)

    return verb_count

filename = list(uploaded.keys())[0]

english_verbs = count_verbs_in_sentence(uploaded[filename])

print("English verb counts per sentence (first 10):", english_verbs[:10])